load("//engine/build:isaac.bzl", "isaac_subgraph")

isaac_subgraph(
    name = "range_scan_subgraph",
    modules = [
        "perception",
        "flatsim",
        "viewers"
    ],
    subgraph = "range_scan.subgraph.json",
    visibility = ["//visibility:public"],
)
